#!/bin/bash

# Installation script for Netpulse
# This script checks dependencies and installs Netpulse

set -e

echo "Netpulse Installation Script"
echo "=========================="

# Check if running as root
if [ "$EUID" -ne 0 ]; then
    echo "This script needs to be run with sudo or as root."
    exit 1
fi

# Function to check if command exists
command_exists() {
    command -v "$1" >/dev/null 2>&1
}

# Function to ask user for input
ask_user() {
    local prompt="$1"
    local default="$2"
    local response
    
    read -p "$prompt [$default]: " response
    echo "${response:-$default}"
}

echo ""
echo "Checking system requirements..."

# Check if we're on a supported system
if [ ! -f /etc/os-release ]; then
    echo "Error: Cannot determine OS version."
    exit 1
fi

source /etc/os-release
echo "Detected OS: $PRETTY_NAME"

# Check architecture
ARCH=$(uname -m)
echo "Architecture: $ARCH"

# Check Python version
if command_exists python3; then
    PYTHON_VERSION=$(python3 -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')")
    echo "Python version: $PYTHON_VERSION"
    
    if [ "$(printf '%s\n' "3.8" "$PYTHON_VERSION" | sort -V | head -n1)" != "3.8" ]; then
        echo "Error: Python 3.8 or higher is required."
        exit 1
    fi
else
    echo "Error: Python 3 is not installed."
    exit 1
fi

# Check for librespeed-cli
echo ""
echo "Checking for librespeed-cli..."
if command_exists librespeed-cli; then
    echo "✓ librespeed-cli found: $(librespeed-cli --version 2>/dev/null || echo 'version unknown')"
    LIBRESPEED_INSTALLED=true
else
    echo "✗ librespeed-cli not found"
    LIBRESPEED_INSTALLED=false
    
    echo ""
    echo "librespeed-cli is required for bandwidth tests."
    echo "Would you like to install it now? (y/n)"
    read -r install_librespeed
    
    if [ "$install_librespeed" = "y" ] || [ "$install_librespeed" = "Y" ]; then
        echo "Installing librespeed-cli..."
        
        if command_exists apt-get; then
            apt-get update
            apt-get install -y librespeed-cli
        else
            echo "Error: Cannot install librespeed-cli automatically."
            echo "Please install it manually from: https://github.com/librespeed/speedtest-cli"
            exit 1
        fi
        
        if command_exists librespeed-cli; then
            echo "✓ librespeed-cli installed successfully"
            LIBRESPEED_INSTALLED=true
        else
            echo "✗ Failed to install librespeed-cli"
            exit 1
        fi
    else
        echo "Warning: Continuing without librespeed-cli. Bandwidth tests will not work."
    fi
fi

# Configuration questions
echo ""
echo "Configuration"
echo "============="

MEASUREMENT_INTERVAL=$(ask_user "Measurement interval (minutes)" "15")
WEB_PORT=$(ask_user "Web interface port" "8080")
AUTO_START=$(ask_user "Auto-start services on boot" "y")

# Create netpulse user
echo ""
echo "Creating netpulse user..."
if ! id netpulse &>/dev/null; then
    useradd --system --home /var/lib/netpulse --shell /usr/sbin/nologin netpulse
    echo "✓ User netpulse created"
else
    echo "✓ User netpulse already exists"
fi

# Create directories
echo ""
echo "Creating directories..."
mkdir -p /var/lib/netpulse
mkdir -p /var/log/netpulse
mkdir -p /etc/netpulse
chown -R netpulse:netpulse /var/lib/netpulse
chown -R netpulse:netpulse /var/log/netpulse
echo "✓ Directories created"

# Install Python dependencies
echo ""
echo "Installing Python dependencies..."
if command_exists pip3; then
    pip3 install -r requirements.txt
else
    echo "Error: pip3 not found. Please install it first:"
    echo "  sudo apt-get install python3-pip"
    exit 1
fi

# Install the package
echo ""
echo "Installing Netpulse..."
python3 setup.py install

# Create configuration file
echo ""
echo "Creating configuration..."
cat > /etc/netpulse/netpulse.conf << EOF
# Netpulse Configuration File
# Generated by installation script on $(date)

# Database settings
database.path=/var/lib/netpulse/netpulse.db
database.backup_enabled=true
database.backup_interval_days=7

# Measurement settings
measurement.interval_minutes=$MEASUREMENT_INTERVAL
measurement.timeout_seconds=30
measurement.retry_count=3
measurement.servers=

# Web interface settings
web.host=0.0.0.0
web.port=$WEB_PORT
web.debug=false
web.secret_key=$(python3 -c "import secrets; print(secrets.token_hex(32))")

# Logging settings
logging.level=INFO
logging.file=/var/log/netpulse/netpulse.log
logging.max_size_mb=10
logging.backup_count=5
EOF

chown root:root /etc/netpulse/netpulse.conf
chmod 644 /etc/netpulse/netpulse.conf
echo "✓ Configuration created"

# Install systemd services
echo ""
echo "Installing systemd services..."
cp systemd/netpulse.service /lib/systemd/system/
cp systemd/netpulse.timer /lib/systemd/system/
cp systemd/netpulse-web.service /lib/systemd/system/
systemctl daemon-reload

if [ "$AUTO_START" = "y" ] || [ "$AUTO_START" = "Y" ]; then
    systemctl enable netpulse.timer
    systemctl enable netpulse-web.service
    systemctl start netpulse.timer
    systemctl start netpulse-web.service
    echo "✓ Services enabled and started"
else
    echo "Services installed but not enabled. To enable:"
    echo "  sudo systemctl enable netpulse.timer"
    echo "  sudo systemctl enable netpulse-web.service"
fi

# Final checks
echo ""
echo "Installation completed!"
echo "====================="

echo ""
echo "Service status:"
systemctl is-active netpulse.timer && echo "✓ netpulse.timer is running" || echo "✗ netpulse.timer is not running"
systemctl is-active netpulse-web.service && echo "✓ netpulse-web.service is running" || echo "✗ netpulse-web.service is not running"

echo ""
echo "Access information:"
echo "  Web interface: http://localhost:$WEB_PORT"
echo "  Configuration: /etc/netpulse/netpulse.conf"
echo "  Log file: /var/log/netpulse/netpulse.log"
echo "  Database: /var/lib/netpulse/netpulse.db"

echo ""
echo "Useful commands:"
echo "  Check status: systemctl status netpulse-web.service"
echo "  View logs: journalctl -u netpulse-web.service -f"
echo "  Run test: netpulse-measure --type bandwidth"
echo "  Stop services: sudo systemctl stop netpulse.timer netpulse-web.service"

if [ "$LIBRESPEED_INSTALLED" = true ]; then
    echo ""
    echo "✓ All dependencies installed and ready to use!"
else
    echo ""
    echo "⚠ librespeed-cli is not installed. Bandwidth tests will not work."
    echo "  Install it with: sudo apt-get install librespeed-cli"
fi

echo ""
echo "Enjoy monitoring your network with Netpulse!"
